### PR TITLE
Fix/use env vars

### PR DESCRIPTION
**Pull request by davidbalazs93**
replaced parameters with environment variables

### CODE REVIEW

**Comment by kghatton** [comment]
Doesn't enforcing the use of env vars make this less flexible?

**Comment by davidbalazs93** [comment]
I'm considering the fact that by using env vars the Docker file looks a little bit clearner. Or maybe we should  use mow.cli ( github.com/jawher/mow.cli ) framework? What are your thoughts?

**Comment by kghatton** [comment]
I'd be fine with using mow.cli or similar, as you suggest. I just think that having env vars as the _only_ way of passing config into the application isn't really a good idea.

**Comment by davidbalazs93** [comment]
ok, I will close this for now

**Pull request closed without merging**
