### PR TITLE
Parallel gzip

### PR DESCRIPTION
**Pull request by ghost**
Use parallel gzip implementation. In testing this reduced the backup
time from ~47m to ~15m

### CODE REVIEW

**Comment by tamas-molnar** [comment]
Shortening the time to make a backup is ok but won't this use more CPU? We're already getting CPU load warnings during backups. Will the service isolation part take care of that?

**Comment by ghost** [comment]
The CPU warned before and will warn after this change, but just not for as long.

Service isolation so far won't do that.  I'm wondering whether we should have all processes like this running with nice and ionice and only warn when non-nice CPU usage is high?

**Comment by tamas-molnar** [comment]
The warning itself isn't the issue, I'm more concerned about the actual CPU usage which causes the warning - what I wanted to say that CPU usage was high and with this change will be even higher. 

Running the backup with nice and ionice should prevent the backup from starving other processes of resources, so let's try that.

**Comment by tamas-molnar** [comment]
Closing as per agreement in the tech forum.

**Pull request closed without merging**
